server:
  port: 10000
  servlet:
    context-path:
spring:
  application:
    name: CloudCenter
  profiles:
    active: prd
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
eureka:
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: localhost
    prefer-ip-address: true
    status-page-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/actuator/health
  client:
    register-with-eureka: false
    fetch-registry: false